In [159]:
import numpy as np
import pandas as pd

In [160]:
df = pd.read_csv('final_test.csv')

In [161]:
df.head()

weight   age  height size
0      62  28.0  172.72   XL
1      59  36.0  167.64    L
2      61  34.0  165.10    M
3      65  27.0  175.26    L
4      62  45.0  172.72    M

In [162]:
df.isnull().sum()

weight      0
age       257
height    330
size        0
dtype: int64

In [163]:
df.dropna(inplace=True)

In [164]:
df.isnull().sum()

weight    0
age       0
height    0
size      0
dtype: int64

In [165]:
df.shape

(119153, 4)

In [166]:
X = df[['weight', 'age', 'height']]

In [167]:
X.isnull().sum()

weight    0
age       0
height    0
dtype: int64

In [168]:
y = df['size']

In [169]:
y.shape

(119153,)

In [170]:
from sklearn.feature_selection import SelectKBest, f_classif

In [171]:
best = SelectKBest(score_func=f_classif, k='all')

In [172]:
best.fit(X, y)

SelectKBest(k='all')

In [173]:
X_features = best.transform(X)

In [174]:
X_features.shape

(119153, 3)

In [175]:
from sklearn.preprocessing import LabelEncoder

In [176]:
enconder = LabelEncoder()

In [177]:
enconder.fit(y)

LabelEncoder()

In [178]:
target = enconder.transform(y)

In [179]:
from sklearn.model_selection import train_test_split

In [180]:
X_train, X_test, y_train, y_test = train_test_split(X_features, target, test_size=0.3, random_state=32)

In [181]:
X_train.shape

(83407, 3)

In [182]:
y_train.shape

(83407,)

In [183]:
from sklearn.linear_model import LogisticRegression

In [184]:
#lr = LogisticRegression(solver='liblinear')

In [185]:
from sklearn.ensemble import RandomForestClassifier

In [186]:
RFC = RandomForestClassifier(n_estimators=1000)

In [187]:
model = RFC.fit(X_train, y_train)

In [188]:
p = model.predict(X_test)

In [189]:
p

array([1, 1, 1, ..., 2, 1, 1])

In [190]:
enconder.inverse_transform(p)

array(['M', 'M', 'M', ..., 'S', 'M', 'M'], dtype=object)

In [191]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [192]:
confusion_matrix(p, y_test)

array([[1486, 1075,  158, 1066,    4,   15,  263],
       [1996, 5246, 2155, 1034,    1,  330,  164],
       [ 203, 1678, 3263,  131,    0, 1424,   20],
       [1284,  575,   65, 2288,    6,   10, 1116],
       [   2,    0,    0,    1,    0,    0,    1],
       [  17,  195,  925,   14,    0, 1310,    6],
       [ 309,  117,   17, 1102,    7,    3, 4664]], dtype=int64)

In [193]:
accuracy_score(p, y_test)

0.5107424606949029

In [194]:
print(classification_report(p, y_test))

              precision    recall  f1-score   support

           0       0.28      0.37      0.32      4067
           1       0.59      0.48      0.53     10926
           2       0.50      0.49      0.49      6719
           3       0.41      0.43      0.42      5344
           4       0.00      0.00      0.00         4
           5       0.42      0.53      0.47      2467
           6       0.75      0.75      0.75      6219

    accuracy                           0.51     35746
   macro avg       0.42      0.43      0.42     35746
weighted avg       0.53      0.51      0.52     35746



In [195]:
query = 51, 29, 5.4

In [196]:
res = model.predict([query])

In [197]:
res

array([1])

In [198]:
predicted_size = enconder.inverse_transform(res)

In [199]:
predicted_size

array(['M'], dtype=object)